import {
  LayoutDashboard,
  FolderHeart,
  FileText,
  Activity,
  Pill,
  CalendarDays,
  Sparkles,
  ShieldCheck,
  ScrollText,
  Settings,
  Stethoscope,
  HeartPulse,
  FlaskConical,
  ClipboardList,
  Users,
} from "lucide-react";

export const ROLE_IDS = [
  "patient",
  "doctor",
  "nurse",
  "laboratory",
  "pharmacist",
  "admin",
];

export const ROLES = {
  patient: {
    id: "patient",
    label: "Patient",
    name: "Maya Chen",
    title: "Personal Health Space",
    subtitle: "Your records, vitals and AI insights in one place",
    icon: HeartPulse,
    route: "/patient",
    ai: {
      title: "My Health Intelligence",
      panelTitle: "Health Intelligence",
      status: "Using authorized records",
      placeholder: "Ask about your health records...",
      suggestions: [
        "What changed recently?",
        "Summarize my latest report",
        "Show my medication history",
        "Compare my recent vitals",
      ],
    },
    accent: {
      text: "text-teal-700",
      softBg: "bg-teal-50",
      softText: "text-teal-700",
      border: "border-teal-200",
      dot: "bg-teal-500",
      hex: "#0d9488",
      badge: "bg-teal-50 text-teal-700 border-teal-200",
    },
    nav: [
      { label: "Overview", href: "/patient", icon: LayoutDashboard, end: true },
      { label: "Health Records", href: "/records", icon: FolderHeart },
      { label: "Reports", href: "/reports", icon: FileText },
      { label: "Vitals", href: "/vitals", icon: Activity },
      { label: "Medications", href: "/medications", icon: Pill },
      { label: "Appointments", href: "/appointments", icon: CalendarDays },
      { label: "Health Intelligence", href: "/assistant", icon: Sparkles },
      { label: "Consent & Access", href: "/consent", icon: ShieldCheck },
      { label: "Audit Activity", href: "/audit", icon: ScrollText },
      { label: "Settings", href: "/settings", icon: Settings },
    ],
  },
  doctor: {
    id: "doctor",
    label: "Doctor",
    name: "Dr. Amara Osei",
    title: "Clinical Workspace",
    subtitle: "Cardiology · Care team of 24 assigned patients",
    icon: Stethoscope,
    route: "/doctor",
    ai: {
      title: "Clinical Intelligence",
      panelTitle: "Clinical Intelligence",
      status: "Authorized patient records · consented scope",
      placeholder: "Ask about an authorized patient record...",
      suggestions: [
        "Summarize this patient's recent history",
        "What changed since the last visit?",
        "Show relevant reports",
      ],
    },
    accent: {
      text: "text-indigo-700",
      softBg: "bg-indigo-50",
      softText: "text-indigo-700",
      border: "border-indigo-200",
      dot: "bg-indigo-500",
      hex: "#6366f1",
      badge: "bg-indigo-50 text-indigo-700 border-indigo-200",
    },
    nav: [
      { label: "Overview", href: "/doctor", icon: LayoutDashboard, end: true },
      { label: "Health Records", href: "/records", icon: FolderHeart },
      { label: "Reports", href: "/reports", icon: FileText },
      { label: "Appointments", href: "/appointments", icon: CalendarDays },
      { label: "Clinical Intelligence", href: "/assistant", icon: Sparkles },
      { label: "Audit Activity", href: "/audit", icon: ScrollText },
      { label: "Settings", href: "/settings", icon: Settings },
    ],
  },
  nurse: {
    id: "nurse",
    label: "Nurse",
    name: "Liam Torres",
    title: "Care Delivery Workspace",
    subtitle: "Ward 3 North · 12 assigned patients",
    icon: ClipboardList,
    route: "/nurse",
    ai: {
      title: "Care Intelligence",
      panelTitle: "Care Intelligence",
      status: "Using assigned patient records",
      placeholder: "Ask about assigned patients...",
      suggestions: [
        "Which vitals need recording today?",
        "Summarize alerts for my patients",
        "Show today's tasks",
      ],
    },
    accent: {
      text: "text-emerald-700",
      softBg: "bg-emerald-50",
      softText: "text-emerald-700",
      border: "border-emerald-200",
      dot: "bg-emerald-500",
      hex: "#10b981",
      badge: "bg-emerald-50 text-emerald-700 border-emerald-200",
    },
    nav: [
      { label: "Overview", href: "/nurse", icon: LayoutDashboard, end: true },
      { label: "Vitals", href: "/vitals", icon: Activity },
      { label: "Health Records", href: "/records", icon: FolderHeart },
      { label: "Appointments", href: "/appointments", icon: CalendarDays },
      { label: "Care Intelligence", href: "/assistant", icon: Sparkles },
      { label: "Audit Activity", href: "/audit", icon: ScrollText },
      { label: "Settings", href: "/settings", icon: Settings },
    ],
  },
  laboratory: {
    id: "laboratory",
    label: "Laboratory",
    name: "Sara Kim",
    title: "Laboratory Workspace",
    subtitle: "CityLab Diagnostics · Sample processing",
    icon: FlaskConical,
    route: "/laboratory",
    ai: {
      title: "Diagnostic Intelligence",
      panelTitle: "Diagnostic Intelligence",
      status: "Using authorized laboratory records",
      placeholder: "Ask about laboratory reports...",
      suggestions: [
        "Show recent report changes",
        "Which reports await verification?",
        "Summarize flagged results",
      ],
    },
    accent: {
      text: "text-violet-700",
      softBg: "bg-violet-50",
      softText: "text-violet-700",
      border: "border-violet-200",
      dot: "bg-violet-500",
      hex: "#8b5cf6",
      badge: "bg-violet-50 text-violet-700 border-violet-200",
    },
    nav: [
      { label: "Overview", href: "/laboratory", icon: LayoutDashboard, end: true },
      { label: "Reports", href: "/reports", icon: FileText },
      { label: "Health Records", href: "/records", icon: FolderHeart },
      { label: "Diagnostic Intelligence", href: "/assistant", icon: Sparkles },
      { label: "Audit Activity", href: "/audit", icon: ScrollText },
      { label: "Settings", href: "/settings", icon: Settings },
    ],
  },
  pharmacist: {
    id: "pharmacist",
    label: "Pharmacist",
    name: "Omar Haddad",
    title: "Pharmacy Workspace",
    subtitle: "Lumina Pharmacy · Dispensing & safety",
    icon: Pill,
    route: "/pharmacist",
    ai: {
      title: "Medication Intelligence",
      panelTitle: "Medication Intelligence",
      status: "Medication scope only · consented",
      placeholder: "Ask about medication history...",
      suggestions: [
        "Show recent medication changes",
        "Any refill or interaction alerts?",
        "Summarize dispensing queue",
      ],
    },
    accent: {
      text: "text-amber-700",
      softBg: "bg-amber-50",
      softText: "text-amber-700",
      border: "border-amber-200",
      dot: "bg-amber-500",
      hex: "#f59e0b",
      badge: "bg-amber-50 text-amber-700 border-amber-200",
    },
    nav: [
      { label: "Overview", href: "/pharmacist", icon: LayoutDashboard, end: true },
      { label: "Medications", href: "/medications", icon: Pill },
      { label: "Health Records", href: "/records", icon: FolderHeart },
      { label: "Medication Intelligence", href: "/assistant", icon: Sparkles },
      { label: "Audit Activity", href: "/audit", icon: ScrollText },
      { label: "Settings", href: "/settings", icon: Settings },
    ],
  },
  admin: {
    id: "admin",
    label: "Administrator",
    name: "Priya Nair",
    title: "System Administration",
    subtitle: "Platform governance, roles and security",
    icon: Users,
    route: "/admin",
    ai: {
      title: "System Intelligence",
      panelTitle: "System Intelligence",
      status: "System events · anonymized views",
      placeholder: "Ask about system activity...",
      suggestions: [
        "Show recent activity",
        "Any unusual access patterns?",
        "Summarize pending access requests",
      ],
    },
    accent: {
      text: "text-rose-700",
      softBg: "bg-rose-50",
      softText: "text-rose-700",
      border: "border-rose-200",
      dot: "bg-rose-500",
      hex: "#f43f5e",
      badge: "bg-rose-50 text-rose-700 border-rose-200",
    },
    nav: [
      { label: "Overview", href: "/admin", icon: LayoutDashboard, end: true },
      { label: "Audit Activity", href: "/audit", icon: ScrollText },
      { label: "Consent & Access", href: "/consent", icon: ShieldCheck },
      { label: "System Intelligence", href: "/assistant", icon: Sparkles },
      { label: "Settings", href: "/settings", icon: Settings },
    ],
  },
};

export function getRole(id) {
  return ROLES[id] || ROLES.patient;
}
